# Generated by Django 3.2.7 on 2021-09-11 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empcode', models.CharField(blank=True, default='No NAME', max_length=50)),
                ('name', models.CharField(blank=True, default='No NAME', max_length=50)),
                ('address', models.CharField(max_length=70)),
                ('pincode', models.CharField(max_length=6)),
                ('mobilenum', models.IntegerField(max_length=10)),
                ('salary', models.CharField(blank=True, default='No NAME', max_length=50)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=15)),
            ],
        ),
    ]
