# Generated by Django 3.2.7 on 2021-09-11 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='mobilenum',
            field=models.IntegerField(),
        ),
    ]
